repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.37.0
    hooks:
      - id: eslint
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint@9.37.0
          - eslint-plugin-svelte@2.35.1
          - svelte-eslint-parser@0.33.1
