# Dependency resolution
defaultSemverRangePrefix: '^' # Use ^ for minor updates (default)

# Performance
compressionLevel: 0 # Faster installs, better for zero-installs
nodeLinker: 'node-modules' # or "pnp" for Plug'n'Play (more advanced)

# Developer Experience
enableProgressBars: true
enableColors: true
